<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default3.aspx.cs" Inherits="Default3" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script></script>
</head>
<body>
    <form id="form1" runat="server">
    <div>

        <asp:ScriptManager ID="sm1" runat="server"></asp:ScriptManager>
        <asp:UpdatePanel ID="um1" runat="server">

            <ContentTemplate>
                <asp:Label ID="label1" runat="server">Look to employee by id to view/edit</asp:Label>
                <asp:TextBox ID="emp_textbox" runat="server" autopostback="true"  ></asp:TextBox>
                <br />
                <asp:Button ID="myButton" autopostback="true"  runat="server" Text="Submit" OnClick="myButton_Click" />
                <asp:GridView ID="myGrid" autopostback="true"  AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowDeleting="myGrid_RowDeleting"   OnRowUpdating ="myGrid_RowUpdating" EnableViewState="true" OnRowCancelingEdit="myGrid_RowCancelingEdit" runat="server"  DataKeyNames="id"  OnRowEditing="myGrid_RowEditing" ></asp:GridView>
            
            </ContentTemplate>
            <Triggers>
                 <asp:AsyncPostBackTrigger ControlID="myGrid" />
            </Triggers>
        </asp:UpdatePanel>
    </div>

    </form>
</body>
</html>
